"""
GitHub service — fetches PR metadata and posts trust score comments.
"""
import httpx
from app.config import settings
from app.services.scorer import TrustResult, DECISION_EMOJI

GITHUB_API = "https://api.github.com"

HEADERS = {
    "Authorization": f"token {settings.github_token}",
    "Accept":        "application/vnd.github.v3+json",
    "X-GitHub-Api-Version": "2022-11-28",
}

DECISION_COLOR = {
    "APPROVE":                 "🟢",
    "APPROVE_WITH_CONDITIONS": "🟡",
    "REVIEW_REQUIRED":         "🟠",
    "BLOCK_DEPLOYMENT":        "🔴",
}


async def get_pr_meta(owner: str, repo: str, pr_number: int) -> dict:
    """Fetch pull request details from GitHub."""
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}",
            headers=HEADERS,
        )
        resp.raise_for_status()
        return resp.json()


async def post_trust_comment(
    owner: str,
    repo: str,
    pr_number: int,
    result: TrustResult,
    snyk_findings: list,
) -> bool:
    """Post (or update) the ADG trust score comment on a PR."""
    body = _build_comment(result, snyk_findings)

    async with httpx.AsyncClient(timeout=15) as client:
        # Check if ADG already commented — update instead of duplicate
        existing_id = await _find_existing_comment(client, owner, repo, pr_number)

        if existing_id:
            resp = await client.patch(
                f"{GITHUB_API}/repos/{owner}/{repo}/issues/comments/{existing_id}",
                headers=HEADERS,
                json={"body": body},
            )
        else:
            resp = await client.post(
                f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
                headers=HEADERS,
                json={"body": body},
            )

        return resp.status_code in (200, 201)


async def _find_existing_comment(
    client: httpx.AsyncClient,
    owner: str,
    repo: str,
    pr_number: int,
) -> int | None:
    """Return comment ID if ADG already commented on this PR."""
    resp = await client.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
        headers=HEADERS,
        params={"per_page": 50},
    )
    if resp.status_code != 200:
        return None
    for comment in resp.json():
        if "<!-- ADG -->" in comment.get("body", ""):
            return comment["id"]
    return None


def _build_comment(result: TrustResult, snyk_findings: list) -> str:
    emoji   = DECISION_EMOJI.get(result.decision, "")
    color   = DECISION_COLOR.get(result.decision, "")
    score   = result.trust_score
    decision_label = result.decision.replace("_", " ")

    # Score bar (20 chars)
    filled = int(score / 5)
    bar    = "█" * filled + "░" * (20 - filled)

    lines = [
        "<!-- ADG -->",
        f"## {emoji} ADG — Deployment Trust Score",
        "",
        f"| | |",
        f"|---|---|",
        f"| **Trust score** | `{score}/100` |",
        f"| **Decision** | {color} **{decision_label}** |",
        f"| **Dep risk** | `{result.dependency_risk}/100` |",
        f"| **PR size risk** | `{result.pr_size_risk}/100` |",
        f"| **Branch age risk** | `{result.branch_age_risk}/100` |",
        "",
        f"```",
        f"Score  [{bar}] {score}/100",
        f"```",
        "",
        "### Findings",
        "",
        result.rationale or "_No issues found._",
    ]

    # Top 5 CVEs
    if snyk_findings:
        lines += ["", "### Top vulnerabilities", ""]
        lines.append("| Severity | Package | CVE | Fix |")
        lines.append("|---|---|---|---|")
        for f in snyk_findings[:5]:
            sev_icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}.get(f.severity, "⚪")
            fix = f.fix_version or "No fix yet"
            cve = f.cve or f.title[:40]
            lines.append(f"| {sev_icon} {f.severity} | `{f.package}@{f.version}` | {cve} | {fix} |")

    lines += [
        "",
        "---",
        "<sub>🤖 Generated by **ADG** — Autonomous DevSecOps Guardian</sub>",
    ]

    return "\n".join(lines)
